<ItemDrawer>:
    theme_text_color: "Custom"
    on_release: self.parent.set_color_item(self)

    IconLeftWidget:
        id: icon
        icon: root.icon
        theme_text_color: "Custom"
        text_color: root.text_color


<ContentNavigationDrawer>:
    orientation: "vertical"
    padding: "8dp"
    spacing: "8dp"

    AnchorLayout:
        anchor_x: "left"
        size_hint_y: None
        height: avatar.height

        Image:
            id: avatar
            size_hint: None, None
            size: "56dp", "56dp"
            source: "icons/recetas.png"

    MDLabel:
        text: "MyRecipes"
        font_style: "Button"
        size_hint_y: None
        height: self.texture_size[1]

    MDLabel:
        text: "github.com/TheBlopa"
        font_style: "Caption"
        size_hint_y: None
        height: self.texture_size[1]

    ScrollView:

        DrawerList:
            id: md_list
            OneLineIconListItem:



NavigationLayout:

    ScreenManager:

        Screen:

            FloatLayout:
                canvas.before:
                    Color:
                        rgba: (.9, .9, .9, 1)
                    Rectangle:
                        size: self.size
                        pos: self.pos

                GridLayout:
                    spacing: 10
                    cols: 1
                    MDToolbar:
                        md_bg_color: app.theme_cls.primary_color
                        title: "Mis Recetas"
                        elevation: 10
                        left_action_items: [['menu', lambda x: nav_drawer.toggle_nav_drawer()]]

        
                GridLayout:
                    pos_hint: {"top": .905, "center_x":.5}
                    size_hint: .97, .89
                    cols: 2
                    spacing: 15
                    BoxLayout:
                        canvas.before:
                            Color: 
                                rgba: .3,.3,.3,1
                            Line:
                                width: 1.2
                                rounded_rectangle: (self.pos[0],self.pos[1],self.size[0],self.size[1],10)
                            Color: 
                                rgba: .99,.99,.99,1
                            RoundedRectangle: 
                                pos: self.pos
                                size: self.size
                                radius: [10]
                        orientation: 'vertical'
                        cols: 1
                        ImageButton:
                            id: meat_button
                            source: "icons/carne.png"
                            on_release:
                                # app.application.get()
                                print('hi')
                        Label:
                            text: "Recetas de carne"
                            font_size: "18sp"
                            color: rgba('#000000')
                            haling: ('center')
                            size_hint_y: None
                            height: dp(30)
                    BoxLayout:
                        canvas.before:
                            Color: 
                                rgba: .3,.3,.3,1
                            Line:
                                width: 1.2
                                rounded_rectangle: (self.pos[0],self.pos[1],self.size[0],self.size[1],10)
                            Color: 
                                rgba: .99,.99,.99,1
                            RoundedRectangle: 
                                pos: self.pos
                                size: self.size
                                radius: [10]
                        orientation: 'vertical'
                        cols: 1
                        ImageButton:
                            id: meat_button
                            source: "icons/pescado.png"
                            on_release:
                                # app.application.get()
                                print('hi')
                        Label:
                            text: "Recetas de pescado"
                            font_size: "18sp"
                            color: rgba('#000000')
                            haling: ('center')
                            size_hint_y: None
                            height: dp(30)
                    BoxLayout:
                        canvas.before:
                            Color: 
                                rgba: .3,.3,.3,1
                            Line:
                                width: 1.2
                                rounded_rectangle: (self.pos[0],self.pos[1],self.size[0],self.size[1],10)
                            Color: 
                                rgba: .99,.99,.99,1
                            RoundedRectangle: 
                                pos: self.pos
                                size: self.size
                                radius: [10]
                        orientation: 'vertical'
                        cols: 1
                        ImageButton:
                            id: meat_button
                            source: "icons/variedad.png"
                            on_release:
                                # app.application.get()
                                print('hi')
                        Label:
                            text: "Recetas de verduras"
                            font_size: "18sp"
                            color: rgba('#000000')
                            haling: ('center')
                            size_hint_y: None
                            height: dp(30)
                    BoxLayout:
                        canvas.before:
                            Color: 
                                rgba: .3,.3,.3,1
                            Line:
                                width: 1.2
                                rounded_rectangle: (self.pos[0],self.pos[1],self.size[0],self.size[1],10)
                            Color: 
                                rgba: .99,.99,.99,1
                            RoundedRectangle: 
                                pos: self.pos
                                size: self.size
                                radius: [10]
                        orientation: 'vertical'
                        cols: 1
                        ImageButton:
                            id: meat_button
                            source: "icons/legumes.png"
                            on_release:
                                # app.application.get()
                                print('hi')
                        Label:
                            text: "Recetas de legumbres"
                            font_size: "18sp"
                            color: rgba('#000000')
                            haling: ('center')
                            size_hint_y: None
                            height: dp(30)
                    BoxLayout:
                        canvas.before:
                            Color: 
                                rgba: .3,.3,.3,1
                            Line:
                                width: 1.2
                                rounded_rectangle: (self.pos[0],self.pos[1],self.size[0],self.size[1],10)
                            Color: 
                                rgba: .99,.99,.99,1
                            RoundedRectangle: 
                                pos: self.pos
                                size: self.size
                                radius: [10]
                        orientation: 'vertical'
                        cols: 1
                        ImageButton:
                            id: meat_button
                            source: "icons/desayuno.png"
                            on_release:
                                # app.application.get()
                                print('hi')
                        Label:
                            text: "Recetas varias"
                            font_size: "18sp"
                            color: rgba('#000000')
                            haling: ('center')
                            size_hint_y: None
                            height: dp(30)
                    BoxLayout:
                        canvas.before:
                            Color: 
                                rgba: .3,.3,.3,1
                            Line:
                                width: 1.2
                                rounded_rectangle: (self.pos[0],self.pos[1],self.size[0],self.size[1],10)
                            Color: 
                                rgba: .99,.99,.99,1
                            RoundedRectangle: 
                                pos: self.pos
                                size: self.size
                                radius: [10]
                        orientation: 'vertical'
                        cols: 1
                        ImageButton:
                            id: meat_button
                            source: "icons/ice-cream.png"
                            on_release:
                                # app.application.get()
                                print('hi')
                        Label:
                            text: "Postres"
                            font_size: "18sp"
                            color: rgba('#000000')
                            haling: ('center')
                            size_hint_y: None
                            height: dp(30)
                

    MDNavigationDrawer:
        id: nav_drawer

        ContentNavigationDrawer:
            id: content_drawer

#MDBottomAppBar:
#                    MDToolbar:
#                        title: "Mis Recetas"
#                        icon: "git"
#                        md_bg_color: app.theme_cls.accent_color
#                        elevation: 10
#                        type: "bottom"
#                        mode: "free-end"
#                        on_action_button: print('hola')