#: import utils kivy.utils

<Test>:
    FloatLayout:
        canvas.before:
            Rectangle:
                size: self.size
                pos: self.pos
                source: "icons/diseno.png"
        GridLayout:
            id: test
            cols: 1
            pos_hint: {"top":.85, "left": 1}
            size_hint:1, .15
            Image:
                source: "icons/cooking.png"
        ScrollView:
            pos_hint: {"top": .7, "center_x": .5}
            size_hint: .6, .55
            GridLayout:
                id: l_recipe
                size_hint_y: None
                cols: 1
                row_default_height: root.height*0.2
                height: self.minimum_height
            
        GridLayout:
            id: grid_test
            cols: 2
            pos_hint: {"top":.13, "left": 1}
            size_hint: 1, .1
            ImageButton:
                id: back
                source: "icons/back.png"
                on_release:
                    app.getText()
            ImageButton:
                id: next
                source: "icons/next.png"
                on_release:
                    app.ping()
            